import color from "color";

    import { Platform, Dimensions, PixelRatio } from "react-native";

    const deviceHeight = Dimensions.get("window").height;
    const deviceWidth = Dimensions.get("window").width;
    const platform = Platform.OS;
    const platformStyle = "material";
    const isIphoneX =
      platform === "ios" && deviceHeight === 812 && deviceWidth === 375;

export default {
  "platformStyle": "material",
  "platform": "ios",
  "androidRipple": true,
  "androidRippleColor": "rgba(256, 256, 256, 0.3)",
  "androidRippleColorDark": "rgba(0, 0, 0, 0.15)",
  "btnUppercaseAndroidText": true,
  "badgeBg": "#ED1727",
  "badgeColor": "#000",
  "badgePadding": 3,
  "btnDisabledBg": "#b5b5b5",
  "buttonPadding": 6,
  "btnPrimaryBg": "rgba(0,0,0,1)",
  "btnPrimaryColor": "#fff",
  "btnInfoBg": "#3F57D3",
  "btnInfoColor": "#fff",
  "btnSuccessBg": "#5cb85c",
  "btnSuccessColor": "#fff",
  "btnDangerBg": "#d9534f",
  "btnDangerColor": "#fff",
  "btnWarningBg": "#f0ad4e",
  "btnWarningColor": "#fff",
  "btnTextSize": 16.5,
  "btnTextSizeLarge": 22.5,
  "btnTextSizeSmall": 12,
  "borderRadiusLarge": 57,
  "iconSizeLarge": 45,
  "iconSizeSmall": 18,
  "cardDefaultBg": "rgba(0,0,0,1)",
  "cardBorderColor": "#ccc",
  "CheckboxRadius": 100,
  "CheckboxBorderWidth": 2,
  "CheckboxPaddingLeft": 2,
  "CheckboxPaddingBottom": 0,
  "CheckboxIconSize": 18,
  "CheckboxFontSize": 21,
  "DefaultFontSize": 17,
  "checkboxBgColor": "rgba(255,255,255,1)",
  "checkboxSize": 20,
  "checkboxTickColor": "rgba(0,0,0,1)",
  "brandPrimary": "rgba(155,155,155,1)",
  "brandInfo": "#3F57D3",
  "brandSuccess": "#5cb85c",
  "brandDanger": "#d9534f",
  "brandWarning": "#f0ad4e",
  "brandDark": "#000",
  "brandLight": "#f4f4f4",
  "fontSizeBase": 15,
  "fontSizeH1": 27,
  "fontSizeH2": 24,
  "fontSizeH3": 21,
  "footerHeight": 65,
  "footerDefaultBg": "#000",
  "footerPaddingBottom": 0,
  "tabBarTextColor": "#000",
  "tabBarTextSize": 14,
  "activeTab": "#000",
  "sTabBarActiveTextColor": "rgba(255,255,255,1)",
  "tabBarActiveTextColor": "#000",
  "tabActiveBgColor": "#fff",
  "toolbarBtnColor": "#fff",
  "toolbarDefaultBg": "#fff",
  "toolbarHeight": 64,
  "toolbarSearchIconSize": 20,
  "toolbarInputColor": "#000",
  "searchBarHeight": 30,
  "searchBarInputHeight": 30,
  "toolbarBtnTextColor": "#fff",
  "toolbarDefaultBorder": "rgba(0,0,0,1)",
  "iosStatusbar": "light-content",
  "statusBarColor": "#32408F",
  "darkenHeader": "#F0F0F0",
  "iconFamily": "Ionicons",
  "iconFontSize": 30,
  "iconHeaderSize": 29,
  "inputFontSize": 17,
  "inputBorderColor": "#fff",
  "inputSuccessBorderColor": "#2b8339",
  "inputErrorBorderColor": "#ed2f2f",
  "inputHeightBase": 50,
  "inputColor": "#000",
  "inputColorPlaceholder": "#575757",
  "btnLineHeight": 19,
  "lineHeightH1": 32,
  "lineHeightH2": 27,
  "lineHeightH3": 22,
  "lineHeight": 20,
  "listBg": "rgba(0,0,0,1)",
  "listBorderColor": "rgba(255,255,255,1)",
  "listDividerBg": "#f4f4f4",
  "listBtnUnderlayColor": "#DDD",
  "listItemPadding": 10,
  "listNoteColor": "#808080",
  "listNoteSize": 13,
  "defaultProgressColor": "#E4202D",
  "inverseProgressColor": "#1A191B",
  "radioBtnSize": 25,
  "radioSelectedColorAndroid": "#5067FF",
  "radioBtnLineHeight": 29,
  "segmentBackgroundColor": "rgba(0,0,0,1)",
  "segmentActiveBackgroundColor": "#fff",
  "segmentTextColor": "#000",
  "segmentActiveTextColor": "rgba(74,74,74,1)",
  "segmentBorderColor": "#fff",
  "segmentBorderColorMain": "#3F51B5",
  "defaultSpinnerColor": "rgba(0,0,0,1)",
  "inverseSpinnerColor": "#1A191B",
  "tabDefaultBg": "#3F51B5",
  "topTabBarTextColor": "#b3c7f9",
  "topTabBarActiveTextColor": "#000",
  "topTabBarBorderColor": "#fff",
  "topTabBarActiveBorderColor": "#fff",
  "tabBgColor": "#F8F8F8",
  "tabFontSize": 15,
  "textColor": "rgba(255,255,255,1)",
  "inverseTextColor": "#000",
  "noteFontSize": 14,
  "defaultTextColor": "#000",
  "titleFontSize": 19,
  "subTitleFontSize": 14,
  "subtitleColor": "#000",
  "titleFontColor": "rgba(255,255,255,1)",
  "borderRadiusBase": 6,
  "borderWidth": 1,
  "contentPadding": 10,
  "dropdownLinkColor": "#414142",
  "inputLineHeight": 24,
  "deviceWidth": 2560,
  "deviceHeight": 945,
  "isIphoneX": false,
  "inputGroupRoundedBorderRadius": 30
}